version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  serverless: circleci/serverless-framework@1.0.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/frontend
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo/frontend
          paths:
            - build
  deploy-frontend:
    docker:
      - image: circleci/golang:1.9.6
    parallelism: 1
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/frontend
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -v github.com/bep/s3deploy
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy to S3
          command: |
            s3deploy -source=build/ -region=$AWS_DEFAULT_REGION -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$AWS_S3_BUCKET_NAME

  build-and-deploy-lambdas:
    executor: serverless/default
    working_directory: ~/repo/lambdas
    steps:
      - checkout:
          path: ~/repo
      - aws-cli/setup
      - serverless/setup
      - run:
          name: Create serverless production config
          command: head -n -2 serverless.yml >> serverless-prd.yml
      - run:
          name: Deploy
          command: serverless deploy --region $AWS_DEFAULT_REGION --stage prd --config serverless-prd.yml --verbose

workflows:
  version: 2
  build-and-deploy-frontend:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - master
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
                - master

  build-and-deploy-lambdas:
    jobs:
      - build-and-deploy-lambdas:
          filters:
            branches:
              only:
                - master
