service: kahvilat-api

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: local
  environment:
    CICD_STAGE: local
    GOOGLE_API_KEY: google-api-key
    GOOGLE_BASE_URL: https://maps.googleapis.com/maps/api
    GOOGLE_LANGUAGE: fi
    REDIS_HOST: localhost
    REDIS_PORT: 6380
    UI_BASE_URL: http://localhost:3000

functions:
  main:
    handler: src/main.handler
    httpApi:
      payload: '1.0'
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
