service: kahvilat-app-google-api-mock

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'local'}
  apiGateway:
    shouldStartNameWithService: true

package:
  excludeDevDependencies: false

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          path: /maps/api/geocode/{format}
          method: get
          cors: true
          request:
            parameters:
              paths:
                format: true
              querystrings:
                key: false
                language: false
                address: false
                latlng: false
      - http:
          path: /maps/api/place/nearbysearch/{format}
          method: get
          cors: true
          request:
            parameters:
              paths:
                format: true
              querystrings:
                key: false
                language: false
                keyword: false
                location: false
                pagetoken: false
                radius: false
                types: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline
